export enum LogAction {
  ADD_PRODUCT_TO_LOCATION = 'ADD_PRODUCT_TO_LOCATION',
  REMOVE_PRODUCT_FROM_LOCATION = 'REMOVE_PRODUCT_FROM_LOCATION',
  RETRIEVE_PRODUCT_LOCATION = 'RETRIEVE_PRODUCT_LOCATION',
}
